app_homepage:
    path: /
    methods: [GET]
    defaults:
        _controller: AppBundle:Default:homepage

app_movie:
    resource: app.movie
    type: sylius.api

app_genre:
    resource: app.genre
    type: sylius.api

app_api_genre_movies:
    path: /genres/{id}/movies/
    defaults:
        _controller: app.controller.movie:indexAction
        _sylius:
            criteria:
                genre: $id
