AppBundle\Entity\Movie:
    properties:
        title:
            - NotBlank: ~
        description:
            - NotBlank: ~
        releaseDate:
            - NotBlank: ~

AppBundle\Entity\Genre:
    properties:
        name:
            - NotBlank: ~
