AppBundle\Entity\Genre:
    exclusion_policy: ALL
    xml_root_name: genre
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
        name:
            expose: true
            type: string
    relations:
        - rel: self
          href:
              route: app_api_genre_show
              parameters:
                  id: expr(object.getId())
